# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import robot_pb2 as robot__pb2


class MachineControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJointList = channel.unary_unary(
                '/robot.MachineController/GetJointList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=robot__pb2.JointList.FromString,
                )
        self.GetJointStatus = channel.unary_stream(
                '/robot.MachineController/GetJointStatus',
                request_serializer=robot__pb2.Joint.SerializeToString,
                response_deserializer=robot__pb2.JointStatus.FromString,
                )
        self.GetJointOption = channel.unary_unary(
                '/robot.MachineController/GetJointOption',
                request_serializer=robot__pb2.Joint.SerializeToString,
                response_deserializer=robot__pb2.JointOption.FromString,
                )
        self.MoveJointPosition = channel.unary_unary(
                '/robot.MachineController/MoveJointPosition',
                request_serializer=robot__pb2.MovePositionCommand.SerializeToString,
                response_deserializer=robot__pb2.CommandResult.FromString,
                )
        self.MoveJointsPosition = channel.unary_unary(
                '/robot.MachineController/MoveJointsPosition',
                request_serializer=robot__pb2.MovePositionCommands.SerializeToString,
                response_deserializer=robot__pb2.CommandResult.FromString,
                )
        self.MoveJointVelocity = channel.unary_unary(
                '/robot.MachineController/MoveJointVelocity',
                request_serializer=robot__pb2.MoveVelocityCommand.SerializeToString,
                response_deserializer=robot__pb2.CommandResult.FromString,
                )
        self.MoveJointsVelocity = channel.unary_unary(
                '/robot.MachineController/MoveJointsVelocity',
                request_serializer=robot__pb2.MoveVelocityCommands.SerializeToString,
                response_deserializer=robot__pb2.CommandResult.FromString,
                )
        self.StopJoint = channel.unary_unary(
                '/robot.MachineController/StopJoint',
                request_serializer=robot__pb2.StopCommand.SerializeToString,
                response_deserializer=robot__pb2.CommandResult.FromString,
                )
        self.EnableJoint = channel.unary_unary(
                '/robot.MachineController/EnableJoint',
                request_serializer=robot__pb2.EnableCommand.SerializeToString,
                response_deserializer=robot__pb2.CommandResult.FromString,
                )
        self.DisableJoint = channel.unary_unary(
                '/robot.MachineController/DisableJoint',
                request_serializer=robot__pb2.DisableCommand.SerializeToString,
                response_deserializer=robot__pb2.CommandResult.FromString,
                )


class MachineControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJointList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveJointPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveJointsPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveJointVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveJointsVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopJoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableJoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableJoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MachineControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJointList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=robot__pb2.JointList.SerializeToString,
            ),
            'GetJointStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.GetJointStatus,
                    request_deserializer=robot__pb2.Joint.FromString,
                    response_serializer=robot__pb2.JointStatus.SerializeToString,
            ),
            'GetJointOption': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointOption,
                    request_deserializer=robot__pb2.Joint.FromString,
                    response_serializer=robot__pb2.JointOption.SerializeToString,
            ),
            'MoveJointPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveJointPosition,
                    request_deserializer=robot__pb2.MovePositionCommand.FromString,
                    response_serializer=robot__pb2.CommandResult.SerializeToString,
            ),
            'MoveJointsPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveJointsPosition,
                    request_deserializer=robot__pb2.MovePositionCommands.FromString,
                    response_serializer=robot__pb2.CommandResult.SerializeToString,
            ),
            'MoveJointVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveJointVelocity,
                    request_deserializer=robot__pb2.MoveVelocityCommand.FromString,
                    response_serializer=robot__pb2.CommandResult.SerializeToString,
            ),
            'MoveJointsVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveJointsVelocity,
                    request_deserializer=robot__pb2.MoveVelocityCommands.FromString,
                    response_serializer=robot__pb2.CommandResult.SerializeToString,
            ),
            'StopJoint': grpc.unary_unary_rpc_method_handler(
                    servicer.StopJoint,
                    request_deserializer=robot__pb2.StopCommand.FromString,
                    response_serializer=robot__pb2.CommandResult.SerializeToString,
            ),
            'EnableJoint': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableJoint,
                    request_deserializer=robot__pb2.EnableCommand.FromString,
                    response_serializer=robot__pb2.CommandResult.SerializeToString,
            ),
            'DisableJoint': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableJoint,
                    request_deserializer=robot__pb2.DisableCommand.FromString,
                    response_serializer=robot__pb2.CommandResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.MachineController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MachineController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJointList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.MachineController/GetJointList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            robot__pb2.JointList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJointStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/robot.MachineController/GetJointStatus',
            robot__pb2.Joint.SerializeToString,
            robot__pb2.JointStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJointOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.MachineController/GetJointOption',
            robot__pb2.Joint.SerializeToString,
            robot__pb2.JointOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveJointPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.MachineController/MoveJointPosition',
            robot__pb2.MovePositionCommand.SerializeToString,
            robot__pb2.CommandResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveJointsPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.MachineController/MoveJointsPosition',
            robot__pb2.MovePositionCommands.SerializeToString,
            robot__pb2.CommandResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveJointVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.MachineController/MoveJointVelocity',
            robot__pb2.MoveVelocityCommand.SerializeToString,
            robot__pb2.CommandResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveJointsVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.MachineController/MoveJointsVelocity',
            robot__pb2.MoveVelocityCommands.SerializeToString,
            robot__pb2.CommandResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopJoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.MachineController/StopJoint',
            robot__pb2.StopCommand.SerializeToString,
            robot__pb2.CommandResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableJoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.MachineController/EnableJoint',
            robot__pb2.EnableCommand.SerializeToString,
            robot__pb2.CommandResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableJoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.MachineController/DisableJoint',
            robot__pb2.DisableCommand.SerializeToString,
            robot__pb2.CommandResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
